// ─────────────────────────────────────────────────────────────────────────────
// examples/transform-hook
//
// Shows the transform hook on defineRoute():
//   - Runs AFTER validation, BEFORE the handler
//   - Use for: password hashing, field normalisation, data enrichment
//   - Service layer stays pure — receives already-transformed data
//
// Three real-world transform patterns shown:
//   1. Password hashing on registration
//   2. Slug generation from title
//   3. Email normalisation
//
// Run:  npx tsx src/index.ts
// Try:
//   # Registration — password is hashed before handler runs
//   curl -X POST http://localhost:3000/register \
//     -H "Content-Type: application/json" \
//     -d '{"email":"Alice@Example.COM","name":"Alice","password":"secret123"}'
//
//   # Article — slug auto-generated from title
//   curl -X POST http://localhost:3000/articles \
//     -H "Content-Type: application/json" \
//     -d '{"title":"Hello World","content":"My first article"}'
// ─────────────────────────────────────────────────────────────────────────────

import express from 'express'
import { z } from 'zod'
import {
  shapeguard,
  createDTO,
  defineRoute,
  handle,
  AppError,
  notFoundHandler,
  errorHandler,
} from 'shapeguard'

// ── Pattern 1: Password hashing ───────────────────────────────────────────────
// Transform hashes the password AFTER validation but BEFORE the handler.
// The handler and service never see the plaintext password.

const RegisterDTO = createDTO(z.object({
  email:    z.string().email(),
  name:     z.string().min(1).max(100),
  password: z.string().min(8),
}))

const UserResponseSchema = z.object({
  id:        z.string().uuid(),
  email:     z.string(),
  name:      z.string(),
  createdAt: z.string().datetime(),
  // password NOT here — never sent to client
})

const RegisterRoute = defineRoute({
  body:      RegisterDTO,
  response:  UserResponseSchema,

  // transform: runs after validation, before handler
  transform: async (data: any) => {
    // Simulate bcrypt.hash (using a simple prefix for this example)
    // In real code: const hash = await bcrypt.hash(data.password, 10)
    const hash = `bcrypt_hashed:${data.password}`
    return {
      ...data,
      email:    data.email.toLowerCase().trim(),  // normalise email too
      password: hash,
    }
  },
})

const register = handle(RegisterRoute, async (req, res) => {
  // req.body.password is already hashed — service is pure
  const user = {
    id:        crypto.randomUUID(),
    email:     req.body.email,    // already normalised by transform
    name:      req.body.name,
    password:  req.body.password, // already hashed by transform
    createdAt: new Date().toISOString(),
  }
  // In real code: await UserService.create(user)
  res.created({ data: user, message: 'Registered successfully' })
})

// ── Pattern 2: Slug generation ────────────────────────────────────────────────
// Transform auto-generates a URL slug from the article title.
// Handler never needs to think about slug generation.

const ArticleDTO = createDTO(z.object({
  title:   z.string().min(1).max(200),
  content: z.string().min(1),
}))

const ArticleResponseSchema = z.object({
  id:        z.string().uuid(),
  title:     z.string(),
  slug:      z.string(),
  content:   z.string(),
  createdAt: z.string().datetime(),
})

const CreateArticleRoute = defineRoute({
  body:      ArticleDTO,
  response:  ArticleResponseSchema,

  transform: async (data: any) => ({
    ...data,
    // Auto-generate slug: "Hello World!" → "hello-world"
    slug: data.title
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-'),
  }),
})

const createArticle = handle(CreateArticleRoute, async (req, res) => {
  // req.body.slug already generated by transform
  const article = {
    id:        crypto.randomUUID(),
    title:     req.body.title,
    slug:      (req.body as any).slug,
    content:   req.body.content,
    createdAt: new Date().toISOString(),
  }
  res.created({ data: article, message: 'Article created' })
})

// ── App setup ─────────────────────────────────────────────────────────────────
const app = express()
app.use(express.json())
app.use(shapeguard())
app.post('/register',  ...register)
app.post('/articles',  ...createArticle)
app.use(notFoundHandler())
app.use(errorHandler())

app.listen(3000, () => {
  console.log('transform-hook example → http://localhost:3000')
  console.log('')
  console.log('POST /register  — password hashed + email normalised by transform')
  console.log('POST /articles  — slug auto-generated from title by transform')
})
